
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
from django.contrib.messages import constants as message_constants
from django.core.exceptions import ImproperlyConfigured

# Cargar variables del archivo .env
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Creamos una constante para los templates
TEMPLATES_DIR = os.path.join(BASE_DIR,'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('Falta SECRET_KEY en el archivo .env')

# SECURITY WARNING: don't run with debug turned on in production!
# Solo es True si en el .env dice exactamente DEBUG=True
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Hosts separados por coma en el .env, ej: ALLOWED_HOSTS=localhost,127.0.0.1
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarioApp',
    'adminApp',
    'terapeutaApp',
    # --- API REST (Evaluación 3) ---
    'rest_framework',                              # Django REST Framework
    'rest_framework_simplejwt.token_blacklist',    # permite invalidar refresh tokens
    'drf_spectacular',                             # Swagger / OpenAPI
    'apiApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarioApp.middleware.RestriccionPorRolMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarioApp.context_processors.rol_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', default_storage_engine=INNODB",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 7,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'adminApp.validators.ComplejidadPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
LOGIN_URL = 'login'

MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# =====================================================================
# API REST: Django REST Framework + JWT + Swagger (Evaluación Sumativa 3)
# =====================================================================
REST_FRAMEWORK = {
    # Autenticación: JWT enviado en la cabecera  Authorization: Bearer <token>
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # "Seguro por defecto": todo endpoint exige estar autenticado, salvo que
    # la vista diga explícitamente lo contrario.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Solo JSON. La interfaz HTML de DRF (browsable API) queda únicamente en desarrollo.
    'DEFAULT_RENDERER_CLASSES': (
        ['rest_framework.renderers.JSONRenderer']
        + (['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else [])
    ),
    # Errores siempre en JSON y sin filtrar detalles internos (500 genérico, 409 en borrados con reservas).
    'EXCEPTION_HANDLER': 'apiApp.exceptions.manejador_excepciones',
    # Las listas se entregan paginadas: evita respuestas gigantes.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Límites de uso: global (anónimos y autenticados) y específico para login/renovación de token.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '300/min',
        'token': '10/min',
    },
}

SIMPLE_JWT = {
    # El access token dura poco: si lo roban, deja de servir pronto.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '15'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '1'))),
    # Cada renovación entrega un refresh nuevo y manda el anterior a la lista negra.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,          # registra el último acceso del usuario (campo last_login)
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,          # la clave sale del .env, no está escrita en el código
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': "API Spa Maison D'Equilibre",
    'DESCRIPTION': (
        "API RESTful del sistema de reservas del spa: terapias, terapeutas y reservas.\n\n"
        "**Cómo autenticarse:** 1) llama a `POST /api/token/` con usuario y contraseña; "
        "2) copia el valor de `access`; 3) pulsa **Authorize** y pégalo; "
        "4) ya puedes probar los endpoints protegidos."
    ),
    'VERSION': '1.0.0',
    'CONTACT': {'name': "Equipo Maison D'Equilibre"},
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,    # necesario para documentar subida de imágenes y archivos
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,   # no pierde el token al recargar la página
    },
}