
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.contrib.messages import constants as message_constants
from django.core.exceptions import ImproperlyConfigured
from datetime import timedelta

# Cargar variables del archivo .env
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Creamos una constante para los templates
TEMPLATES_DIR = os.path.join(BASE_DIR,'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('Falta SECRET_KEY en el archivo .env')

# SECURITY WARNING: don't run with debug turned on in production!
# Solo es True si en el .env dice exactamente DEBUG=True
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Hosts separados por coma en el .env, ej: ALLOWED_HOSTS=localhost,127.0.0.1
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarioApp',
    'adminApp',
    'terapeutaApp',
    # --- API REST EV3 ---
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',   # permite invalidar refresh tokens
    'drf_spectacular',
    'spaApi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarioApp.middleware.RestriccionPorRolMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarioApp.context_processors.rol_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES', default_storage_engine=INNODB",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 7,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'adminApp.validators.ComplejidadPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
LOGIN_URL = 'login'

MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =====================================================================
# API REST EV3 ESTO ES PARA QUE FUNCIONE EL JWT.
# =====================================================================
REST_FRAMEWORK = {
    # Cómo se identifica quien llama a la API: con un token JWT en la cabecera Authorization
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Por defecto, TODO endpoint exige estar autenticado
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Genera la documentación (Swagger) a partir del código
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Todos los errores pasan por un único manejador: siempre JSON y sin datos internos
    'EXCEPTION_HANDLER': 'spaApi.exceptions.manejador_excepciones',
    # Respuestas solo en JSON. La página de pruebas de DRF (HTML) solo se permite con DEBUG=True.
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ] + (['rest_framework.renderers.BrowsableAPIRenderer'] if DEBUG else []),
    # Límite de peticiones por minuto (contra abuso y fuerza bruta)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',    # sin token: se cuenta por dirección IP
        'rest_framework.throttling.UserRateThrottle',    # con token: se cuenta por usuario
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '300/min',
        'token': '10/min',      # login y renovación de token: el más estricto
    },
}

  # Documentación de la API (Swagger / OpenAPI)
SPECTACULAR_SETTINGS = {
      'TITLE': "API Spa Maison D'Equilibre",
      'DESCRIPTION': 'API REST del spa: terapias, terapeutas y reservas.',
      'VERSION': '1.0.0',
      'SERVE_INCLUDE_SCHEMA': False,
      'SWAGGER_UI_SETTINGS': {'persistAuthorization': True},   # no pierde el token al recargar
  }

# Los contadores del límite de peticiones se guardan en la caché. Con gunicorn hay VARIOS procesos y
# la caché por defecto (memoria) es distinta en cada uno: el límite se multiplicaría. Una caché en
# archivo la comparten todos.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': BASE_DIR / 'django_cache',
    }
}

# Configuración de los tokens JWT. Se firman con SECRET_KEY (la del .env), por eso nunca se sube a GitHub.
SIMPLE_JWT = {
    # Access token: corta vida. Si lo roban, deja de servir pronto. Para la demostración se puede
    # subir poniendo JWT_ACCESS_MINUTES=60 en el .env.
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '15'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,          # cada vez que se renueva, se entrega un refresh NUEVO...
    'BLACKLIST_AFTER_ROTATION': True,       # ...y el anterior queda invalidado (un refresh sirve una sola vez)
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}